version: '3'
services:
    octoprint:
        image: nunofgs/octoprint:1.3.11-debian
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - /opt/octoprint/data:/data
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"

